---
kind: pipeline
type: docker
name: default


steps:
- name: build
  image: golang
  commands:
  - mkdir armhf arm64 amd64
  - go install github.com/coredhcp/coredhcp/cmds/coredhcp@${DRONE_TAG}
  - mv /go/bin/coredhcp amd64/
  - env GOOS=linux GOARCH=arm go install github.com/coredhcp/coredhcp/cmds/coredhcp@${DRONE_TAG}
  - mv /go/bin/linux_arm/coredhcp armhf/
  - env GOOS=linux GOARCH=arm64 go install github.com/coredhcp/coredhcp/cmds/coredhcp@${DRONE_TAG}
  - mv /go/bin/linux_arm64/coredhcp arm64/

- name: pack
  image: goreleaser/nfpm
  commands:
  - VERSION=$(echo $DRONE_TAG | awk -F'-' '{ print $1 }')
  - RELEASE=$(echo $DRONE_TAG | awk -F'-' '{ print $2 "-" $3 }')
  - export VERSION
  - export RELEASE
  - env
  - ls -la .
  - ln -fs ./armhf/ ./bin
  - ls -la ./bin
  - export ARCH=armhf
  - nfpm package --target coredhcp_${VERSION}_${RELEASE}_armhf.deb
  - ln -fs ./arm64/ ./bin
  - export ARCH=arm64
  - nfpm package --target coredhcp_${VERSION}_${RELEASE}_arm64.deb
  - ln -fs ./amd64/ ./bin
  - export ARCH=amd64
  - nfpm package --target coredhcp_${VERSION}_${RELEASE}_amd64.deb

trigger:
  event:
  - tag
