---
kind: pipeline
type: docker
name: default


steps:
- name: build
  image: golang
  commands:
  - mkdir armhf arm64 amd64
  - go install github.com/coredhcp/coredhcp/cmds/coredhcp@v0.0.0-20210830115404-2176f33418f4
  - mv /go/bin/coredhcp amd64/
  - env GOOS=linux GOARCH=arm go install github.com/coredhcp/coredhcp/cmds/coredhcp@v0.0.0-20210830115404-2176f33418f4
  - mv /go/bin/linux_arm/coredhcp armhf/
  - env GOOS=linux GOARCH=arm64 go install github.com/coredhcp/coredhcp/cmds/coredhcp@v0.0.0-20210830115404-2176f33418f4
  - mv /go/bin/linux_arm64/coredhcp arm64/

- name: pack
  image: goreleaser/nfpm
  commands:
  - export VERSION=$(echo $DRONE_TAG | awk -F'-' '{ print $1 }')
  - export RELEASE=$(echo $DRONE_TAG | awk -F'-' '{ print $2 "-" $3 }')
  - ls -la .
  - ln -fs ./bin ./armhf/
  - env ARCH=armhf nfpm package --traget coredhcp_${VERSION}_${RELEASE}_armhf.deb
  - ln -fs ./bin ./arm64/
  - env ARCH=arm64 nfpm package --traget coredhcp_${VERSION}_${RELEASE}_arm64.deb
  - ln -fs ./bin ./amd64/
  - env ARCH=amd64 nfpm package --traget coredhcp_${VERSION}_${RELEASE}_amd64.deb

trigger:
  event:
  - tag
