---
kind: pipeline
type: docker
name: default


steps:
- name: build
  image: golang
  commands:
  - mkdir armhf arm64 amd64
  - go install github.com/coredhcp/coredhcp/cmds/coredhcp@v0.0.0-20210830115404-2176f33418f4
  - mv bin/coredns amd64/
  - env GOOS=linux GOARCH=arm go install github.com/coredhcp/coredhcp/cmds/coredhcp@v0.0.0-20210830115404-2176f33418f4
  - mv bin/linux_arm/coredns armhf/
  - env GOOS=linux GOARCH=arm64 go install github.com/coredhcp/coredhcp/cmds/coredhcp@v0.0.0-20210830115404-2176f33418f4
  - mv bin/linux_arm64/coredns arm64/

- name: pack
  image: goreleaser/nfpm
  commands:
  - export VERSION=$(echo $DRONE_TAG | awk -F'-' '{ print $1 }')
  - export RELEASE=$(echo $DRONE_TAG | awk -F'-' '{ print $2 "-" $3 }')
  - ls -la .
  - env ARCH=armhf /nfpm pkg --traget coredns_${VERSION}_${RELEASE}_armhf.deb

trigger:
  event:
  - tag
